# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # 检出仓库代码
      - name: checkout repository
        uses: actions/checkout@v4
      # 校验 gradle wrapper 的合法性
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      # 设置 JDK 21 环境
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      # 赋予 gradlew 可执行权限（Linux 下必须）
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      # 执行构建
      - name: build
        run: ./gradlew build
      # 上传构建产物（供后续步骤或手动下载）
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
